### ISSUE TITLE
Stack dump on orphan alignment

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#32]
Doing an orphan layout on the SWD2-ARP alignment, I get the following stack dump. In the code, I see:
```   
List<NetLink> blueEdgesPlusContext = new ArrayList<NetLink>();
blueEdgesPlusContext.get(0);
```
Which is guaranteed to fail...

```Java version = 1.8.0_92 vendor = Oracle Corporation operating system = Mac OS X
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.systemsbiology.biofabric.plugin.core.align.NetworkAlignment$OrphanEdgeLayout.process(NetworkAlignment.java:450)
	at org.systemsbiology.biofabric.plugin.core.align.NetworkAlignment$OrphanEdgeLayout.access$0(NetworkAlignment.java:430)
	at org.systemsbiology.biofabric.plugin.core.align.NetworkAlignment.mergeNetworks(NetworkAlignment.java:178)
	at org.systemsbiology.biofabric.plugin.core.align.NetworkAlignmentPlugIn$NetworkAlignmentRunner.runCore(NetworkAlignmentPlugIn.java:1066)
	at org.systemsbiology.biofabric.worker.BackgroundWorker.runBackground(BackgroundWorker.java:96)
	at org.systemsbiology.biofabric.worker.BackgroundWorker.run(BackgroundWorker.java:81)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by RishiDesai** [comment]
Not sure how that get() statement got there- but it's gone now and the rest of the orphan function seems to be working fine.
