### ISSUE TITLE
Perfect alignment requirement not checked

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#33]
The Cycle Alignment requires a perfect alignment file if the smaller network names are not a subset of the larger network. The dialog says as much. But this is not checked and caught, and causes a stack exception way late. If you could check this condition early, and tell the user to fix the problem, that would be a great help. Thx.

```Java version = 1.8.0_92 vendor = Oracle Corporation operating system = Mac OS X
java.lang.NullPointerException
	at org.systemsbiology.biofabric.plugin.core.align.AlignCycleLayout.calcAlignPaths(AlignCycleLayout.java:600)
	at org.systemsbiology.biofabric.plugin.core.align.AlignCycleLayout.doNodeOrder(AlignCycleLayout.java:162)
	at org.systemsbiology.biofabric.plugin.core.align.AlignCycleLayout.doNodeLayout(AlignCycleLayout.java:124)
	at org.systemsbiology.biofabric.model.BioFabricNetwork.processLinks(BioFabricNetwork.java:609)
	at org.systemsbiology.biofabric.model.BioFabricNetwork.<init>(BioFabricNetwork.java:184)
	at org.systemsbiology.biofabric.io.FileLoadFlowsImpl.expensiveModelOperations(FileLoadFlowsImpl.java:2437)
	at org.systemsbiology.biofabric.io.FileLoadFlowsImpl$NewNetworkRunner.runCore(FileLoadFlowsImpl.java:2056)
	at org.systemsbiology.biofabric.worker.BackgroundWorker.runBackground(BackgroundWorker.java:96)
	at org.systemsbiology.biofabric.worker.BackgroundWorker.run(BackgroundWorker.java:81)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by RishiDesai** [comment]
Fixed with f89d67d4e7e7bb6e0e51740474b13fa7e2151003
